spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: qa
    password: qa
  jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  h2:
  console:
  enabled: true